/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.EtsCliente;
import bean.EtsVendas;
import bean.EtsVendasProduto;
import bean.EtsVendendor;
import dao.ClienteDao;
import dao.VendendorDao;
import dao.vendasDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;
import bean.EtsProduto;
import dao.DaoProduto;
import dao.VendasProdutoDao;



/**
 *
 * @author eduardo
 */
public class JDlgVendas extends javax.swing.JDialog {
 MaskFormatter mascaraData;
    private boolean incluindo;
    DaoProduto produto;
     EtsVendasProduto etsVendasProduto;
 public vendasDao vDao;
 public VendasProdutoDao produtoDao;
   public EtsVendas vendas;
   public EtsProduto etsProduto;
   public ClienteDao clienteDao;
   public VendasProdutoControle controle;
   public JDlgVendasProduto jDlgVendasProduto;
   
    /**
     * Creates new form JDlgVendas
     */
    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Util.habilitar(false, JTxtCodigo,JTxtTotal,JCboCliente,JCboVendendor,JFmtData,JCboCliente,JFmtData,JTxtTotal,JCboVendendor,JBtnExcluir,JBtnCancelar,JBtnConfirmar,jBtnIncluirProd,jBtnAlterarProd,jBtnExcluirprod);
           vDao = new vendasDao();
    List lista = new ArrayList();
      controle = new VendasProdutoControle();
        ClienteDao clientesDAO = new ClienteDao();
        List listaCli = clientesDAO.listAll();
        for (int i = 0; i < listaCli.size(); i++) {
            JCboCliente.addItem((EtsCliente) listaCli.get(i));
        }
        VendendorDao vendedorDAO = new VendendorDao();
        List listaVend = vendedorDAO.listAll();
        for (int i = 0; i < listaVend.size(); i++) {
            JCboVendendor.addItem((EtsVendendor) listaVend.get(i));
        }
        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFmtData.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    jTable1.setModel(controle);
    controle.setList(lista);

    }
    public EtsVendas viewBean() {
        EtsVendas vendas = new EtsVendas();
        vendas.setEtsIdvendas(Integer.parseInt(JTxtCodigo.getText()));
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try{
        vendas.setEtsData(formato.parse(JFmtData.getText()));
        } catch (ParseException ex) {
            System.out.println("TA ERRADO" + ex.getMessage());
        }
        vendas.setEtsCliente((EtsCliente) JCboCliente.getSelectedItem());
        vendas.setEtsVendendor((EtsVendendor) JCboVendendor.getSelectedItem());
        vendas.setEtsTotal(Util.strDouble(JTxtTotal.getText()));
        return vendas;
    }
public void beanView( EtsVendas etsVendas){
    vendas = etsVendas;
JTxtCodigo.setText(String.valueOf(etsVendas.getEtsIdvendas()));
        JFmtData.setText(Util.dateStr(etsVendas.getEtsData()));
        JCboCliente.setSelectedItem(etsVendas.getEtsCliente());
        JCboVendendor.setSelectedItem(etsVendas.getEtsVendendor());
        JTxtTotal.setText(String.valueOf(etsVendas.getEtsTotal()));
        
        produtoDao = new VendasProdutoDao();
      List listavendas = (List) produtoDao.listProduto(vendas);
        controle.setList(listavendas);
    }
public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jBtnIncluirProd = new javax.swing.JButton();
        JTxtCodigo = new javax.swing.JTextField();
        jBtnAlterarProd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnExcluirprod = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JBtnIncluir = new javax.swing.JButton();
        JBtnAlterar = new javax.swing.JButton();
        JBtnExcluir = new javax.swing.JButton();
        JBtnConfirmar = new javax.swing.JButton();
        JBtnCancelar = new javax.swing.JButton();
        JBtnPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JTxtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JCboCliente = new javax.swing.JComboBox<EtsCliente>();
        JCboVendendor = new javax.swing.JComboBox<EtsVendendor>();
        JFmtData = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("num.Venda");

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });

        jLabel2.setText("cliente");

        jBtnExcluirprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluirprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirprodActionPerformed(evt);
            }
        });

        jLabel3.setText("data");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        JBtnIncluir.setText("incluir");
        JBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnIncluirActionPerformed(evt);
            }
        });

        JBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        JBtnAlterar.setText("alterar");
        JBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAlterarActionPerformed(evt);
            }
        });

        JBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        JBtnExcluir.setText("excluir");
        JBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnExcluirActionPerformed(evt);
            }
        });

        JBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        JBtnConfirmar.setText("confirmar");
        JBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConfirmarActionPerformed(evt);
            }
        });

        JBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        JBtnCancelar.setText("cancelar");
        JBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCancelarActionPerformed(evt);
            }
        });

        JBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        JBtnPesquisar.setText("pesquisar");
        JBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnPesquisar))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBtnIncluir)
                        .addComponent(JBtnAlterar)
                        .addComponent(JBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBtnCancelar)
                        .addComponent(JBtnPesquisar)))
                .addContainerGap())
        );

        jLabel4.setText("total");

        jLabel5.setText("vendendor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnIncluirProd, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jBtnAlterarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnExcluirprod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(JTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(JCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(JCboVendendor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCboVendendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBtnIncluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluirprod, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnPesquisarActionPerformed
        Util.habilitar(true, JBtnExcluir,JBtnConfirmar,JBtnCancelar);
        JDlgVendasPesquisar jDlgVendasPesquisar = new JDlgVendasPesquisar(null, true);
   jDlgVendasPesquisar.setTelaAnterior(this);        
        jDlgVendasPesquisar.setVisible(true);
              
    }//GEN-LAST:event_JBtnPesquisarActionPerformed

    private void JBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCancelarActionPerformed
Util.habilitar(true,JBtnIncluir,JBtnAlterar,JBtnPesquisar);
Util.habilitar(false, JTxtCodigo,JCboCliente,JFmtData,JTxtTotal,JCboVendendor,JBtnCancelar,JBtnConfirmar,jBtnAlterarProd,jBtnExcluirprod,jBtnIncluirProd,JBtnExcluir);
Util.limparCampos(JTxtCodigo,JCboCliente,JFmtData,JTxtTotal,JCboVendendor,JBtnIncluir,JBtnCancelar,JBtnConfirmar);
  controle.setList(new ArrayList());
        // TODO add your handling code here: 
    }//GEN-LAST:event_JBtnCancelarActionPerformed

    private void JBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnIncluirActionPerformed
        incluindo = true;
        Util.habilitar(true, JTxtCodigo,JCboCliente,JFmtData,JTxtTotal,JCboVendendor,JBtnIncluir,JBtnCancelar,JBtnConfirmar,jBtnIncluirProd,jBtnAlterarProd,jBtnExcluirprod);
 Util.habilitar(false, JBtnPesquisar,JBtnIncluir,JBtnAlterar,JBtnExcluir);
      Util.limparCampos(JTxtCodigo,JCboCliente,JFmtData,JTxtTotal,JCboVendendor,JBtnIncluir,JBtnCancelar,JBtnConfirmar);
    controle.setList(new ArrayList());
        JTxtCodigo.grabFocus();
       vendas  = new EtsVendas();      // TODO add your handling code here:
    }//GEN-LAST:event_JBtnIncluirActionPerformed

    private void JBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAlterarActionPerformed

if (vendas != null) {

           vDao = new vendasDao();
                EtsVendasProduto evp;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    evp = controle.getBean(linha);
                    vDao.delete(evp);} 
           Util.habilitar(true, JTxtCodigo,JCboCliente,JFmtData,JTxtTotal,JCboVendendor,JBtnIncluir,JBtnAlterar,JBtnExcluir,JBtnCancelar,JBtnPesquisar,JBtnConfirmar,jBtnIncluirProd,jBtnAlterarProd,jBtnExcluirprod);
Util.habilitar(false, JBtnAlterar);
        } else {
            Util.mensagem("Faz uma pesquisa ai");
        }
        incluindo = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnAlterarActionPerformed

    private void JBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConfirmarActionPerformed
      vendas = viewBean();
        
        if (incluindo == true) {
            vDao.insert(vendas);
            produtoDao = new VendasProdutoDao();
            EtsVendasProduto vendasProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                vendasProduto = controle.getBean(linha);
                vendasProduto.setEtsVendas(vendas);
                produtoDao.insert(vendasProduto);

            }

        } else {
            produtoDao.update(vendas);
            produtoDao = new VendasProdutoDao();
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                etsVendasProduto = controle.getBean(linha);
                etsVendasProduto.setEtsVendas(vendas);
               produtoDao.insert(etsVendasProduto);
            }


        }
                  Util.limparCampos(JTxtCodigo,JFmtData,JTxtTotal,JCboCliente,JCboVendendor);
        Util.habilitar(false,JTxtCodigo,JCboCliente,JFmtData,JTxtTotal,JCboVendendor,JBtnIncluir,JBtnCancelar,JBtnConfirmar,jBtnAlterarProd,jBtnExcluirprod,jBtnIncluirProd,JBtnExcluir);
        Util.habilitar(true, JBtnIncluir,JBtnExcluir,JBtnPesquisar,JBtnAlterar);
         controle.setList(new ArrayList());
         vendas = null;       
// TODO add your handling code here:
    }//GEN-LAST:event_JBtnConfirmarActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed

        jDlgVendasProduto = new JDlgVendasProduto(null, true);
        jDlgVendasProduto.setTitle("inclusão de produtos");
        jDlgVendasProduto.setTelaAnterior(this);
        jDlgVendasProduto.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        jDlgVendasProduto  = new JDlgVendasProduto(null, true);
jDlgVendasProduto.setTitle("alteração");
jDlgVendasProduto.setTelaAnterior(this);

     etsVendasProduto = (EtsVendasProduto) controle.getBean(getSelectedRowProd());
jDlgVendasProduto.beanView(etsVendasProduto);
jDlgVendasProduto.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    private void jBtnExcluirprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirprodActionPerformed
        if (getSelectedRowProd() == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.perguntar("Confirma exclusão do produto?") == true) {
                controle.removeBean(getSelectedRowProd());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluirprodActionPerformed

    private void JBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnExcluirActionPerformed
if (vendas != null) {
            if (Util.perguntar("Deseja excluir o pedido ?") == true) {
                vDao = new vendasDao();
                EtsVendasProduto etsVendasProdutos;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    etsVendasProdutos = controle.getBean(linha);
                    vDao.delete(etsVendasProdutos);
                }
                vDao.delete(vendas);
            }
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        controle.setList(new ArrayList());
        Util.limparCampos(JTxtCodigo, JFmtData, JCboCliente, JCboVendendor, JTxtTotal);
        vendas = null;
    }//GEN-LAST:event_JBtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas dialog = new JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAlterar;
    private javax.swing.JButton JBtnCancelar;
    private javax.swing.JButton JBtnConfirmar;
    private javax.swing.JButton JBtnExcluir;
    private javax.swing.JButton JBtnIncluir;
    private javax.swing.JButton JBtnPesquisar;
    private javax.swing.JComboBox<EtsCliente> JCboCliente;
    private javax.swing.JComboBox<EtsVendendor> JCboVendendor;
    private javax.swing.JFormattedTextField JFmtData;
    private javax.swing.JTextField JTxtCodigo;
    private javax.swing.JTextField JTxtTotal;
    private javax.swing.JButton jBtnAlterarProd;
    private javax.swing.JButton jBtnExcluirprod;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
