package bean;
// Generated 16/09/2023 15:18:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtsCliente generated by hbm2java
 */
@Entity
@Table(name="ets_cliente"
    ,catalog="lp"
)
public class EtsCliente  implements java.io.Serializable {


     private int etsIdCliente;
     private String etsNome;
     private String etsCpf;
     private Date etsDatanascimento;
     private String etsCelular;
     private String etsRg;
     private String etsCep;
     private String etsCidade;
     private String etsEmail;
     private String etsTelefoneResedencial;
     private String etsNacionalidade;
     private String etsRegiao;
     private String etsSexo;
     private String etsBairro;
     private String etsEstado;

    public EtsCliente() {
    }

	
    public EtsCliente(int etsIdCliente, String etsNome, String etsCpf, Date etsDatanascimento, String etsCelular, String etsRg, String etsCep, String etsCidade, String etsEmail, String etsTelefoneResedencial, String etsNacionalidade, String etsRegiao, String etsSexo, String etsBairro, String etsEstado) {
        this.etsIdCliente = etsIdCliente;
        this.etsNome = etsNome;
        this.etsCpf = etsCpf;
        this.etsDatanascimento = etsDatanascimento;
        this.etsCelular = etsCelular;
        this.etsRg = etsRg;
        this.etsCep = etsCep;
        this.etsCidade = etsCidade;
        this.etsEmail = etsEmail;
        this.etsTelefoneResedencial = etsTelefoneResedencial;
        this.etsNacionalidade = etsNacionalidade;
        this.etsRegiao = etsRegiao;
        this.etsSexo = etsSexo;
        this.etsBairro = etsBairro;
        this.etsEstado = etsEstado;
    }
    public EtsCliente(int etsIdCliente, String etsNome, String etsCpf, Date etsDatanascimento, String etsCelular, String etsRg, String etsCep, String etsCidade, String etsEmail, String etsTelefoneResedencial, String etsNacionalidade, String etsRegiao, String etsSexo, String etsBairro, String etsEstado, Set etsVendases) {
       this.etsIdCliente = etsIdCliente;
       this.etsNome = etsNome;
       this.etsCpf = etsCpf;
       this.etsDatanascimento = etsDatanascimento;
       this.etsCelular = etsCelular;
       this.etsRg = etsRg;
       this.etsCep = etsCep;
       this.etsCidade = etsCidade;
       this.etsEmail = etsEmail;
       this.etsTelefoneResedencial = etsTelefoneResedencial;
       this.etsNacionalidade = etsNacionalidade;
       this.etsRegiao = etsRegiao;
       this.etsSexo = etsSexo;
       this.etsBairro = etsBairro;
       this.etsEstado = etsEstado;
    }
   
     @Id 

    
    @Column(name="ets_id_cliente", unique=true, nullable=false)
    public int getEtsIdCliente() {
        return this.etsIdCliente;
    }
    
    public void setEtsIdCliente(int etsIdCliente) {
        this.etsIdCliente = etsIdCliente;
    }

    
    @Column(name="ets_nome", nullable=false, length=50)
    public String getEtsNome() {
        return this.etsNome;
    }
    
    public void setEtsNome(String etsNome) {
        this.etsNome = etsNome;
    }

    
    @Column(name="ets_cpf", nullable=false, length=14)
    public String getEtsCpf() {
        return this.etsCpf;
    }
    
    public void setEtsCpf(String etsCpf) {
        this.etsCpf = etsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ets_datanascimento", nullable=false, length=10)
    public Date getEtsDatanascimento() {
        return this.etsDatanascimento;
    }
    
    public void setEtsDatanascimento(Date etsDatanascimento) {
        this.etsDatanascimento = etsDatanascimento;
    }

    
    @Column(name="ets_celular", nullable=false, length=20)
    public String getEtsCelular() {
        return this.etsCelular;
    }
    
    public void setEtsCelular(String etsCelular) {
        this.etsCelular = etsCelular;
    }

    
    @Column(name="ets_rg", nullable=false, length=7)
    public String getEtsRg() {
        return this.etsRg;
    }
    
    public void setEtsRg(String etsRg) {
        this.etsRg = etsRg;
    }

    
    @Column(name="ets_cep", nullable=false, length=9)
    public String getEtsCep() {
        return this.etsCep;
    }
    
    public void setEtsCep(String etsCep) {
        this.etsCep = etsCep;
    }

    
    @Column(name="ets_cidade", nullable=false, length=45)
    public String getEtsCidade() {
        return this.etsCidade;
    }
    
    public void setEtsCidade(String etsCidade) {
        this.etsCidade = etsCidade;
    }

    
    @Column(name="ets_email", nullable=false, length=70)
    public String getEtsEmail() {
        return this.etsEmail;
    }
    
    public void setEtsEmail(String etsEmail) {
        this.etsEmail = etsEmail;
    }

    
    @Column(name="ets_telefoneResedencial", nullable=false, length=20)
    public String getEtsTelefoneResedencial() {
        return this.etsTelefoneResedencial;
    }
    
    public void setEtsTelefoneResedencial(String etsTelefoneResedencial) {
        this.etsTelefoneResedencial = etsTelefoneResedencial;
    }

    
    @Column(name="ets_nacionalidade", nullable=false, length=100)
    public String getEtsNacionalidade() {
        return this.etsNacionalidade;
    }
    
    public void setEtsNacionalidade(String etsNacionalidade) {
        this.etsNacionalidade = etsNacionalidade;
    }

    
    @Column(name="ets_regiao", nullable=false, length=100)
    public String getEtsRegiao() {
        return this.etsRegiao;
    }
    
    public void setEtsRegiao(String etsRegiao) {
        this.etsRegiao = etsRegiao;
    }

    
    @Column(name="ets_sexo", nullable=false, length=6)
    public String getEtsSexo() {
        return this.etsSexo;
    }
    
    public void setEtsSexo(String etsSexo) {
        this.etsSexo = etsSexo;
    }

    
    @Column(name="ets_bairro", nullable=false, length=30)
    public String getEtsBairro() {
        return this.etsBairro;
    }
    
    public void setEtsBairro(String etsBairro) {
        this.etsBairro = etsBairro;
    }

    
    @Column(name="ets_estado", nullable=false, length=50)
    public String getEtsEstado() {
        return this.etsEstado;
    }
    
    public void setEtsEstado(String etsEstado) {
        this.etsEstado = etsEstado;
    }
}


