package bean;
// Generated 07/12/2023 21:49:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtsProduto generated by hbm2java
 */
@Entity
@Table(name="ets_produto"
    ,catalog="lp"
)
public class EtsProduto  implements java.io.Serializable {


     private int etsIdProduto;
     private String etsNome;
     private Double etsPreco;
     private Date etsValidade;
     private String etsQuantidade;

    public EtsProduto() {
    }

	
    public EtsProduto(int etsIdProduto, String etsNome, Double etsPreco, Date etsValidade, String etsQuantidade) {
        this.etsIdProduto = etsIdProduto;
        this.etsNome = etsNome;
        this.etsPreco = etsPreco;
        this.etsValidade = etsValidade;
        this.etsQuantidade = etsQuantidade;
    }
     @Id 

    
    @Column(name="ets_id_produto", unique=true, nullable=false)
    public int getEtsIdProduto() {
        return this.etsIdProduto;
    }
    
    public void setEtsIdProduto(int etsIdProduto) {
        this.etsIdProduto = etsIdProduto;
    }

    
    @Column(name="ets_nome", nullable=false, length=45)
    public String getEtsNome() {
        return this.etsNome;
    }
    
    public void setEtsNome(String etsNome) {
        this.etsNome = etsNome;
    }

    
    @Column(name="ets_preco", nullable=false, precision=10)
    public Double getEtsPreco() {
        return this.etsPreco;
    }
    
    public void setEtsPreco(Double etsPreco) {
        this.etsPreco = etsPreco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ets_validade", nullable=false, length=10)
    public Date getEtsValidade() {
        return this.etsValidade;
    }
    
    public void setEtsValidade(Date etsValidade) {
        this.etsValidade = etsValidade;
    }

    
    @Column(name="ets_quantidade", nullable=false, length=45)
    public String getEtsQuantidade() {
        return this.etsQuantidade;
    }
    
    public void setEtsQuantidade(String etsQuantidade) {
        this.etsQuantidade = etsQuantidade;
    }

    @Override
    public String toString() {
        return etsNome; //To change body of generated methods, choose Tools | Templates.
    }



}


