package bean;
// Generated 07/12/2023 21:49:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtsUsuario generated by hbm2java
 */
@Entity
@Table(name="ets_usuario"
    ,catalog="lp"
)
public class EtsUsuario  implements java.io.Serializable {


     private int etsIdusuario;
     private String etsNome;
     private String etsApelido;
     private String etsCpf;
     private Date etsDatanascimento;
     private String etsSenha;
     private int etsNivel;
     private String etsAtivo;
   

    public EtsUsuario() {
    }

	
    public EtsUsuario(int etsIdusuario, String etsNome, String etsApelido, String etsCpf, Date etsDatanascimento, String etsSenha, int etsNivel, String etsAtivo) {
        this.etsIdusuario = etsIdusuario;
        this.etsNome = etsNome;
        this.etsApelido = etsApelido;
        this.etsCpf = etsCpf;
        this.etsDatanascimento = etsDatanascimento;
        this.etsSenha = etsSenha;
        this.etsNivel = etsNivel;
        this.etsAtivo = etsAtivo;
    }
   
     @Id 

    
    @Column(name="ets_idusuario", unique=true, nullable=false)
    public int getEtsIdusuario() {
        return this.etsIdusuario;
    }
    
    public void setEtsIdusuario(int etsIdusuario) {
        this.etsIdusuario = etsIdusuario;
    }

    
    @Column(name="ets_nome", nullable=false, length=45)
    public String getEtsNome() {
        return this.etsNome;
    }
    
    public void setEtsNome(String etsNome) {
        this.etsNome = etsNome;
    }

    
    @Column(name="ets_apelido", nullable=false, length=25)
    public String getEtsApelido() {
        return this.etsApelido;
    }
    
    public void setEtsApelido(String etsApelido) {
        this.etsApelido = etsApelido;
    }

    
    @Column(name="ets_cpf", nullable=false, length=18)
    public String getEtsCpf() {
        return this.etsCpf;
    }
    
    public void setEtsCpf(String etsCpf) {
        this.etsCpf = etsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ets_datanascimento", nullable=false, length=10)
    public Date getEtsDatanascimento() {
        return this.etsDatanascimento;
    }
    
    public void setEtsDatanascimento(Date etsDatanascimento) {
        this.etsDatanascimento = etsDatanascimento;
    }

    
    @Column(name="ets_senha", nullable=false, length=30)
    public String getEtsSenha() {
        return this.etsSenha;
    }
    
    public void setEtsSenha(String etsSenha) {
        this.etsSenha = etsSenha;
    }

    
    @Column(name="ets_nivel", nullable=false)
    public int getEtsNivel() {
        return this.etsNivel;
    }
    
    public void setEtsNivel(int etsNivel) {
        this.etsNivel = etsNivel;
    }

    
    @Column(name="ets_ativo", nullable=false, length=1)
    public String getEtsAtivo() {
        return this.etsAtivo;
    }
    
    public void setEtsAtivo(String etsAtivo) {
        this.etsAtivo = etsAtivo;
    }

    @Override
    public String toString() {
        return etsApelido; //To change body of generated methods, choose Tools | Templates.
    }


}


