package bean;
// Generated 07/12/2023 21:49:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EtsVendasProduto generated by hbm2java
 */
@Entity
@Table(name="ets_vendas_produto"
    ,catalog="lp"
)
public class EtsVendasProduto  implements java.io.Serializable {


     private int etsIdVendasProduto;
     private EtsProduto etsProduto;
     private EtsVendas etsVendas;
     private Double etsValorUnitario;
     private String etsQuantidade;

    public EtsVendasProduto() {
    }

	
    public EtsVendasProduto(int etsIdVendasProduto, EtsProduto etsProduto, Double etsValorUnitario, String etsQuantidade) {
        this.etsIdVendasProduto = etsIdVendasProduto;
        this.etsProduto = etsProduto;
        this.etsValorUnitario = etsValorUnitario;
        this.etsQuantidade = etsQuantidade;
    }
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ets_id_vendas_produto", unique=true, nullable=false)
    public int getEtsIdVendasProduto() {
        return this.etsIdVendasProduto;
    }
    
    public void setEtsIdVendasProduto(int etsIdVendasProduto) {
        this.etsIdVendasProduto = etsIdVendasProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ets_fk_produtos", nullable=false)
    public EtsProduto getEtsProduto() {
        return this.etsProduto;
    }
    
    public void setEtsProduto(EtsProduto etsProduto) {
        this.etsProduto = etsProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ets_fk_venda")
    public EtsVendas getEtsVendas() {
        return this.etsVendas;
    }
    
    public void setEtsVendas(EtsVendas etsVendas) {
        this.etsVendas = etsVendas;
    }

    
    @Column(name="ets_valorUnitario", nullable=false, precision=5)
    public Double getEtsValorUnitario() {
        return this.etsValorUnitario;
    }
    
    public void setEtsValorUnitario(Double etsValorUnitario) {
        this.etsValorUnitario = etsValorUnitario;
    }

    
    @Column(name="ets_quantidade", nullable=false, length=100)
    public String getEtsQuantidade() {
        return this.etsQuantidade;
    }
    
    public void setEtsQuantidade(String etsQuantidade) {
        this.etsQuantidade = etsQuantidade;
    }




}


