package bean;
// Generated 16/09/2023 15:18:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EtsVendasProduto generated by hbm2java
 */
@Entity
@Table(name="ets_vendas_produto"
    ,catalog="lp"
)
public class EtsVendasProduto  implements java.io.Serializable {


     private int etsIdVendasProduto;
     private EtsProduto etsProduto;
     private double etsValorUnitario;
     private String etsQuantidade;

    public EtsVendasProduto() {
    }

    public EtsVendasProduto(int etsIdVendasProduto, EtsProduto etsProduto, double etsValorUnitario, String etsQuantidade) {
       this.etsIdVendasProduto = etsIdVendasProduto;
       this.etsProduto = etsProduto;
       this.etsValorUnitario = etsValorUnitario;
       this.etsQuantidade = etsQuantidade;
    }
   
     @Id 

    
    @Column(name="ets_id_vendas_produto", unique=true, nullable=false)
    public int getEtsIdVendasProduto() {
        return this.etsIdVendasProduto;
    }
    
    public void setEtsIdVendasProduto(int etsIdVendasProduto) {
        this.etsIdVendasProduto = etsIdVendasProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ets_fk_produtos", nullable=false)
    public EtsProduto getEtsProduto() {
        return this.etsProduto;
    }
    
    public void setEtsProduto(EtsProduto etsProduto) {
        this.etsProduto = etsProduto;
    }

    
    @Column(name="ets_valorUnitario", nullable=false, precision=5)
    public double getEtsValorUnitario() {
        return this.etsValorUnitario;
    }
    
    public void setEtsValorUnitario(double etsValorUnitario) {
        this.etsValorUnitario = etsValorUnitario;
    }

    
    @Column(name="ets_quantidade", nullable=false, length=100)
    public String getEtsQuantidade() {
        return this.etsQuantidade;
    }
    
    public void setEtsQuantidade(String etsQuantidade) {
        this.etsQuantidade = etsQuantidade;
    }
}


