package bean;
// Generated 07/12/2023 21:49:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtsVendendor generated by hbm2java
 */
@Entity
@Table(name="ets_vendendor"
    ,catalog="lp"
)
public class EtsVendendor  implements java.io.Serializable {


     private int etsIdvendendor;
     private EtsUsuario etsUsuario;
     private String etsTelefone;
     private Double etsComissao;
     private String etsArea;
  

    public EtsVendendor() {
    }

	
    public EtsVendendor(int etsIdvendendor, EtsUsuario etsUsuario, String etsTelefone, Double etsComissao, String etsArea) {
        this.etsIdvendendor = etsIdvendendor;
        this.etsUsuario = etsUsuario;
        this.etsTelefone = etsTelefone;
        this.etsComissao = etsComissao;
        this.etsArea = etsArea;
    }
     @Id 

    
    @Column(name="ets_idvendendor", unique=true, nullable=false)
    public int getEtsIdvendendor() {
        return this.etsIdvendendor;
    }
    
    public void setEtsIdvendendor(int etsIdvendendor) {
        this.etsIdvendendor = etsIdvendendor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ets_fkusuario", nullable=false)
    public EtsUsuario getEtsUsuario() {
        return this.etsUsuario;
    }
    
    public void setEtsUsuario(EtsUsuario etsUsuario) {
        this.etsUsuario = etsUsuario;
    }

    
    @Column(name="ets_telefone", nullable=false, length=45)
    public String getEtsTelefone() {
        return this.etsTelefone;
    }
    
    public void setEtsTelefone(String etsTelefone) {
        this.etsTelefone = etsTelefone;
    }

    
    @Column(name="ets_comissao", nullable=false, precision=10)
    public Double getEtsComissao() {
        return this.etsComissao;
    }
    
    public void setEtsComissao(Double etsComissao) {
        this.etsComissao = etsComissao;
    }

    
    @Column(name="ets_area", nullable=false, length=20)
    public String getEtsArea() {
        return this.etsArea;
    }
    
    public void setEtsArea(String etsArea) {
        this.etsArea = etsArea;
    }

    @Override
    public String toString() {
        return etsUsuario.getEtsNome(); //To change body of generated methods, choose Tools | Templates.
    }


}


