package bean;
// Generated 16/09/2023 15:18:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtsVendas generated by hbm2java
 */
@Entity
@Table(name="ets_vendas"
    ,catalog="lp"
)
public class EtsVendas  implements java.io.Serializable {


     private int etsIdvendas;
     private EtsCliente etsCliente;
     private Date etsData;
     private String etsQuantidade;
     private double etsTotal;
     private EtsVendendor etsVendendor;

    public EtsVendas() {
    }

    public EtsVendas(int etsIdvendas, EtsCliente etsCliente, Date etsData, String etsQuantidade, double etsTotal, EtsVendendor etsVendendor) {
       this.etsIdvendas = etsIdvendas;
       this.etsCliente = etsCliente;
       this.etsData = etsData;
       this.etsQuantidade = etsQuantidade;
       this.etsTotal = etsTotal;
       this.etsVendendor = etsVendendor;
    }
   
     @Id 

    
    @Column(name="ets_idvendas", unique=true, nullable=false)
    public int getEtsIdvendas() {
        return this.etsIdvendas;
    }
    
    public void setEtsIdvendas(int etsIdvendas) {
        this.etsIdvendas = etsIdvendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ets_fkcliente", nullable=false)
    public EtsCliente getEtsCliente() {
        return this.etsCliente;
    }
    
    public void setEtsCliente(EtsCliente etsCliente) {
        this.etsCliente = etsCliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ets_data", nullable=false, length=10)
    public Date getEtsData() {
        return this.etsData;
    }
    
    public void setEtsData(Date etsData) {
        this.etsData = etsData;
    }

    
    @Column(name="ets_quantidade", nullable=false, length=500)
    public String getEtsQuantidade() {
        return this.etsQuantidade;
    }
    
    public void setEtsQuantidade(String etsQuantidade) {
        this.etsQuantidade = etsQuantidade;
    }

    
    @Column(name="ets_total", nullable=false, precision=10)
    public double getEtsTotal() {
        return this.etsTotal;
    }
    
    public void setEtsTotal(double etsTotal) {
        this.etsTotal = etsTotal;
    }

    
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ets_fkvendendor", nullable=false)
    public EtsVendendor getEtsVendendor() {
        return this.etsVendendor;
    }
    
    public void setEtsVendendor(EtsVendendor etsVendendor) {
        this.etsVendendor = etsVendendor;
    }
}


